/**
 * Real vendor model catalog — registered when providers are configured.
 */

import type { LlmModelRegistrationInput } from "@/lib/ai/providers/provider-models";

export const LLM_VENDOR_MODEL_CATALOG: LlmModelRegistrationInput[] = [
  // OpenAI
  {
    id: "openai.gpt-4.1-mini",
    providerId: "openai",
    displayName: "GPT-4.1 Mini",
    maxContextTokens: 1_047_576,
    vision: true,
    streaming: true,
    structuredOutput: true,
    embeddings: false,
    toolCalling: true,
    reasoning: false,
    pricingTier: "standard",
    latencyTier: "low",
    status: "available",
  },
  {
    id: "openai.gpt-4.1",
    providerId: "openai",
    displayName: "GPT-4.1",
    maxContextTokens: 1_047_576,
    vision: true,
    streaming: true,
    structuredOutput: true,
    embeddings: false,
    toolCalling: true,
    reasoning: false,
    pricingTier: "premium",
    latencyTier: "medium",
    status: "available",
  },
  {
    id: "openai.o3",
    providerId: "openai",
    displayName: "OpenAI o3",
    maxContextTokens: 200_000,
    vision: true,
    streaming: true,
    structuredOutput: true,
    embeddings: false,
    toolCalling: true,
    reasoning: true,
    pricingTier: "premium",
    latencyTier: "high",
    status: "available",
  },
  {
    id: "openai.text-embedding-3-small",
    providerId: "openai",
    displayName: "text-embedding-3-small",
    maxContextTokens: 8_191,
    vision: false,
    streaming: false,
    structuredOutput: false,
    embeddings: true,
    toolCalling: false,
    reasoning: false,
    pricingTier: "standard",
    latencyTier: "low",
    status: "available",
    capabilities: { chat: false },
  },
  // Anthropic
  {
    id: "claude.claude-sonnet-4-20250514",
    providerId: "claude",
    displayName: "Claude Sonnet 4",
    maxContextTokens: 200_000,
    vision: true,
    streaming: true,
    structuredOutput: true,
    embeddings: false,
    toolCalling: true,
    reasoning: true,
    pricingTier: "premium",
    latencyTier: "medium",
    status: "available",
  },
  {
    id: "claude.claude-3-5-haiku-latest",
    providerId: "claude",
    displayName: "Claude 3.5 Haiku",
    maxContextTokens: 200_000,
    vision: true,
    streaming: true,
    structuredOutput: true,
    embeddings: false,
    toolCalling: true,
    reasoning: false,
    pricingTier: "standard",
    latencyTier: "low",
    status: "available",
  },
  // Gemini
  {
    id: "gemini.gemini-2.0-flash",
    providerId: "gemini",
    displayName: "Gemini 2.0 Flash",
    maxContextTokens: 1_000_000,
    vision: true,
    streaming: true,
    structuredOutput: true,
    embeddings: false,
    toolCalling: true,
    reasoning: false,
    pricingTier: "standard",
    latencyTier: "low",
    status: "available",
  },
  {
    id: "gemini.gemini-2.5-pro",
    providerId: "gemini",
    displayName: "Gemini 2.5 Pro",
    maxContextTokens: 1_000_000,
    vision: true,
    streaming: true,
    structuredOutput: true,
    embeddings: false,
    toolCalling: true,
    reasoning: true,
    pricingTier: "premium",
    latencyTier: "high",
    status: "available",
  },
  {
    id: "gemini.text-embedding-004",
    providerId: "gemini",
    displayName: "text-embedding-004",
    maxContextTokens: 2_048,
    vision: false,
    streaming: false,
    structuredOutput: false,
    embeddings: true,
    toolCalling: false,
    reasoning: false,
    pricingTier: "standard",
    latencyTier: "low",
    status: "available",
    capabilities: { chat: false },
  },
  // Azure OpenAI (deployment-backed logical ids)
  {
    id: "azure-openai.gpt-4o-mini",
    providerId: "azure-openai",
    displayName: "Azure GPT-4o Mini",
    maxContextTokens: 128_000,
    vision: true,
    streaming: true,
    structuredOutput: true,
    embeddings: false,
    toolCalling: true,
    reasoning: false,
    pricingTier: "standard",
    latencyTier: "low",
    status: "available",
  },
  {
    id: "azure-openai.gpt-4o",
    providerId: "azure-openai",
    displayName: "Azure GPT-4o",
    maxContextTokens: 128_000,
    vision: true,
    streaming: true,
    structuredOutput: true,
    embeddings: false,
    toolCalling: true,
    reasoning: false,
    pricingTier: "premium",
    latencyTier: "medium",
    status: "available",
  },
  // OpenRouter
  {
    id: "openrouter.openai/gpt-4.1-mini",
    providerId: "openrouter",
    displayName: "OpenRouter GPT-4.1 Mini",
    maxContextTokens: 1_047_576,
    vision: true,
    streaming: true,
    structuredOutput: true,
    embeddings: false,
    toolCalling: true,
    reasoning: false,
    pricingTier: "standard",
    latencyTier: "low",
    status: "available",
  },
  {
    id: "openrouter.anthropic/claude-sonnet-4",
    providerId: "openrouter",
    displayName: "OpenRouter Claude Sonnet 4",
    maxContextTokens: 200_000,
    vision: true,
    streaming: true,
    structuredOutput: true,
    embeddings: false,
    toolCalling: true,
    reasoning: true,
    pricingTier: "premium",
    latencyTier: "medium",
    status: "available",
  },
];

/** Strip provider prefix for vendor API model ids when needed. */
export function toVendorModelApiId(modelId: string, providerId: string): string {
  const prefix = `${providerId}.`;
  if (modelId.startsWith(prefix)) return modelId.slice(prefix.length);
  return modelId;
}
