export const AUDIT_ACTIONS = {
  REGISTER: "auth.register",
  LOGIN: "auth.login",
  LOGOUT: "auth.logout",
  ORGANIZATION_CREATED: "organization.created",
  WORKSPACE_CREATED: "workspace.created",
  MEMBERSHIP_CREATED: "membership.created",
  COMPANY_CREATED: "company.created",
  COMPANY_UPDATED: "company.updated",
  COMPANY_SETTINGS_UPDATED: "company.settings.updated",
  COMPANY_ARCHIVED: "company.archived",
  COMPANY_RESTORED: "company.restored",
  ENGAGEMENT_CREATED: "engagement.created",
  ENGAGEMENT_UPDATED: "engagement.updated",
  ENGAGEMENT_STATUS_CHANGED: "engagement.status.changed",
  ENGAGEMENT_ARCHIVED: "engagement.archived",
  ENGAGEMENT_RESTORED: "engagement.restored",
  PLANNING_CREATED: "planning.created",
  PLANNING_UPDATED: "planning.updated",
  PLANNING_ARCHIVED: "planning.archived",
  PLANNING_RESTORED: "planning.restored",
  PLANNING_SUBMITTED: "planning.submitted",
  PLANNING_RETURNED: "planning.returned",
  PLANNING_APPROVED: "planning.approved",
  PLANNING_REVISED: "planning.revised",
  PLANNING_COMMENT_ADDED: "planning.comment.added",
  PLANNING_DOCUMENT_ADDED: "planning.document.added",
} as const;
