/**
 * Enterprise design system — color tokens.
 * Professional audit platform palette — light and dark semantic roles.
 */

export const colorTokens = {
  light: {
    background: "var(--ds-color-background)",
    foreground: "var(--ds-color-foreground)",
    muted: "var(--ds-color-muted)",
    mutedForeground: "var(--ds-color-muted-foreground)",
    card: "var(--ds-color-card)",
    cardForeground: "var(--ds-color-card-foreground)",
    border: "var(--ds-color-border)",
    input: "var(--ds-color-input)",
    ring: "var(--ds-color-ring)",
    primary: "var(--ds-color-primary)",
    primaryForeground: "var(--ds-color-primary-foreground)",
    secondary: "var(--ds-color-secondary)",
    secondaryForeground: "var(--ds-color-secondary-foreground)",
    accent: "var(--ds-color-accent)",
    accentForeground: "var(--ds-color-accent-foreground)",
    destructive: "var(--ds-color-destructive)",
    destructiveForeground: "var(--ds-color-destructive-foreground)",
    success: "var(--ds-color-success)",
    successForeground: "var(--ds-color-success-foreground)",
    warning: "var(--ds-color-warning)",
    warningForeground: "var(--ds-color-warning-foreground)",
    sidebar: "var(--ds-color-sidebar)",
    sidebarForeground: "var(--ds-color-sidebar-foreground)",
    sidebarBorder: "var(--ds-color-sidebar-border)",
  },
  dark: {
    background: "var(--ds-color-background)",
    foreground: "var(--ds-color-foreground)",
    muted: "var(--ds-color-muted)",
    mutedForeground: "var(--ds-color-muted-foreground)",
    card: "var(--ds-color-card)",
    cardForeground: "var(--ds-color-card-foreground)",
    border: "var(--ds-color-border)",
    input: "var(--ds-color-input)",
    ring: "var(--ds-color-ring)",
    primary: "var(--ds-color-primary)",
    primaryForeground: "var(--ds-color-primary-foreground)",
    secondary: "var(--ds-color-secondary)",
    secondaryForeground: "var(--ds-color-secondary-foreground)",
    accent: "var(--ds-color-accent)",
    accentForeground: "var(--ds-color-accent-foreground)",
    destructive: "var(--ds-color-destructive)",
    destructiveForeground: "var(--ds-color-destructive-foreground)",
    success: "var(--ds-color-success)",
    successForeground: "var(--ds-color-success-foreground)",
    warning: "var(--ds-color-warning)",
    warningForeground: "var(--ds-color-warning-foreground)",
    sidebar: "var(--ds-color-sidebar)",
    sidebarForeground: "var(--ds-color-sidebar-foreground)",
    sidebarBorder: "var(--ds-color-sidebar-border)",
  },
} as const;
