import type { GovernanceLabels } from "@/components/governance/recycle-bin-experience";
import type { PlatformLabels } from "@/i18n/platform-labels";

export function governanceLabelsFromPlatform(t: PlatformLabels): GovernanceLabels {
  const g = t.governance;
  return {
    title: g.recycleBinTitle,
    description: g.recycleBinDescription,
    search: g.search,
    emptyTitle: g.emptyTitle,
    emptyDescription: g.emptyDescription,
    colObject: g.colObject,
    colType: g.colType,
    colCompany: g.colCompany,
    colDeletedAt: g.colDeletedAt,
    colDeletedBy: g.colDeletedBy,
    colReason: g.colReason,
    colRetention: g.colRetention,
    colLegalHold: g.colLegalHold,
    colActions: g.colActions,
    restore: g.restore,
    restoreOnly: g.restoreOnly,
    restoreChildren: g.restoreChildren,
    restoreHierarchy: g.restoreHierarchy,
    previewTitle: g.previewTitle,
    permanentDelete: g.permanentDelete,
    export: g.export,
    legalHold: g.legalHold,
    clearLegalHold: g.clearLegalHold,
    legalHoldOn: g.legalHoldOn,
    legalHoldOff: g.legalHoldOff,
    selected: g.selected,
    bulkRestore: g.bulkRestore,
    bulkExport: g.bulkExport,
    bulkPermanentDelete: g.bulkPermanentDelete,
    retentionExpired: g.retentionExpired,
    retentionRemaining: g.retentionRemaining,
    years: g.years,
    months: g.months,
    days: g.days,
    typeDelete: g.typeDelete,
    typeDeleteHint: g.typeDeleteHint,
    finalConfirm: g.finalConfirm,
    cancel: g.cancel,
    confirm: g.confirm,
    reasonLabel: g.reasonLabel,
    reasonOther: g.reasonOther,
    objectsToRestore: g.objectsToRestore,
    dependencies: g.dependencies,
    engagements: g.engagements,
    users: g.users,
    workspaces: g.workspaces,
    companies: g.companies,
    workingPapers: g.workingPapers,
    reports: g.reports,
    documents: g.documents,
    allowBeforeRetention: g.allowBeforeRetention,
    reasons: g.reasons,
    objectTypes: g.objectTypes,
    toastRestored: g.toastRestored,
    toastDeleted: g.toastDeleted,
    toastExported: g.toastExported,
    toastHoldUpdated: g.toastHoldUpdated,
  };
}
