import { UAIE_PERMISSIONS } from "@/constants/uaie";
import { defineAiSkill, workspaceReadPermission } from "@/lib/ai/skills/shared/define-skill";
import type { AiSkillRegistration } from "@/lib/ai/skills/contracts/types";

export const UAIE_AI_SKILLS: readonly AiSkillRegistration[] = [
  defineAiSkill({
    id: "uaie.explain_import",
    name: "Explain Import",
    moduleId: "uaie",
    description: "Explain UAIE import intelligence purpose.",
    category: "explanation",
    capabilities: ["explain"],
    permission: workspaceReadPermission([UAIE_PERMISSIONS.READ]),
    intentHints: ["explain import", "explain uaie", "what is uaie"],
    plannerIntents: ["explain", "answer"],
    priority: 70,
    buildContext: ({ knowledge }) => ({
      title: "Explain Import",
      description: knowledge?.purpose ?? "Universal Audit Import Engine.",
      structuredContext: { focus: "uaie_explanation" },
    }),
  }),
  defineAiSkill({
    id: "uaie.import_summary",
    name: "Import Summary",
    moduleId: "uaie",
    description: "Structured UAIE import summary context.",
    category: "import",
    capabilities: ["summarize", "status"],
    permission: workspaceReadPermission([UAIE_PERMISSIONS.READ]),
    intentHints: ["import summary", "uaie summary", "summarize import"],
    plannerIntents: ["answer"],
    priority: 75,
    buildContext: ({ context }) => ({
      title: "Import Summary",
      description: "Import run summary envelope.",
      structuredContext: {
        focus: "uaie_import_summary",
        companyId: context.companyId,
        stages: ["upload", "scan", "map", "validate", "commit"],
      },
    }),
  }),
  defineAiSkill({
    id: "uaie.unknown_headers",
    name: "Unknown Headers",
    moduleId: "uaie",
    description: "Structured unknown header context from import scanning.",
    category: "import",
    capabilities: ["list", "analyze"],
    permission: workspaceReadPermission([UAIE_PERMISSIONS.READ]),
    intentHints: ["unknown headers", "unmapped headers", "header mapping"],
    plannerIntents: ["search", "suggest"],
    priority: 80,
    buildContext: () => ({
      title: "Unknown Headers",
      severity: "warning",
      description: "Unknown headers envelope — no dictionary writes.",
      structuredContext: {
        focus: "uaie_unknown_headers",
        resolutionPaths: ["map_existing", "create_alias", "ignore"],
      },
    }),
  }),
  defineAiSkill({
    id: "uaie.unknown_words",
    name: "Unknown Words",
    moduleId: "uaie",
    description: "Structured unknown words context from import learning.",
    category: "import",
    capabilities: ["list", "analyze"],
    permission: workspaceReadPermission([UAIE_PERMISSIONS.READ]),
    intentHints: ["unknown words", "uaie unknown words", "unrecognized terms"],
    plannerIntents: ["search", "suggest"],
    priority: 78,
    buildContext: () => ({
      title: "Unknown Words",
      severity: "warning",
      description: "Unknown vocabulary envelope.",
      structuredContext: {
        focus: "uaie_unknown_words",
        learningActions: ["accept", "reject", "defer"],
      },
    }),
  }),
  defineAiSkill({
    id: "uaie.erp_detection",
    name: "ERP Detection",
    moduleId: "uaie",
    description: "Structured ERP detection context.",
    category: "analysis",
    capabilities: ["analyze", "status"],
    permission: workspaceReadPermission([UAIE_PERMISSIONS.READ]),
    intentHints: ["erp detection", "detect erp", "which erp"],
    plannerIntents: ["answer", "explain"],
    priority: 72,
    buildContext: () => ({
      title: "ERP Detection",
      description: "ERP detection envelope — confidence metadata only.",
      structuredContext: {
        focus: "uaie_erp_detection",
        candidateErps: ["sap", "1c", "oracle", "dynamics", "quickbooks", "unknown"],
      },
    }),
  }),
  defineAiSkill({
    id: "uaie.confidence_explanation",
    name: "Confidence Explanation",
    moduleId: "uaie",
    description: "Explain UAIE confidence scoring structure.",
    category: "explanation",
    capabilities: ["explain"],
    permission: workspaceReadPermission([UAIE_PERMISSIONS.READ]),
    intentHints: ["confidence explanation", "uaie confidence", "mapping confidence"],
    plannerIntents: ["explain", "answer"],
    priority: 68,
    buildContext: () => ({
      title: "Confidence Explanation",
      description: "Confidence bands for import intelligence suggestions.",
      structuredContext: {
        focus: "uaie_confidence",
        bands: [
          { id: "high", min: 75 },
          { id: "medium", min: 50 },
          { id: "low", min: 0 },
        ],
      },
    }),
  }),
];
