import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { buildCiBlueprint, PIPELINE_STAGES } from "@/lib/devops/ci";
import type { CiProvider } from "@/lib/devops/types";

function writeFile(path: string, contents: string): string {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, "utf8");
  return path;
}

function githubWorkflow(): string {
  return `# Generated by EDRP — Enterprise DevOps & Release Platform
# Do not duplicate governance logic here — invoke npm scripts that call devopsEngine.
name: EDRP

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: edrp-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validation Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - run: npm ci
      - name: Database governance
        run: npm run validate:database
      - name: EDRP operate (skip live reset in CI by default)
        run: npm run edrp:operate -- --skip-reset
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test
      - name: Build
        run: npm run build
      - name: Upload EDRP artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: edrp-artifacts
          path: |
            src/lib/devops/data/artifacts/**
            src/lib/devops/data/snapshots/latest.json
          if-no-files-found: warn

  # Stages mirrored for visibility (same engine — not duplicated logic)
  stage-matrix:
    name: Stage contract
    runs-on: ubuntu-latest
    needs: validate
    strategy:
      matrix:
        stage:
${PIPELINE_STAGES.map((stage) => `          - ${stage}`).join("\n")}
    steps:
      - run: echo "EDRP stage \${{ matrix.stage }} is enforced by devopsEngine pipeline"
`;
}

function azurePipelines(): string {
  return `# Generated by EDRP — Azure DevOps
trigger:
  - main
  - master

pr:
  - main
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Validate
    displayName: EDRP Validation
    jobs:
      - job: Pipeline
        timeoutInMinutes: 45
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "20.x"
          - script: npm ci
            displayName: Install
          - script: npm run validate:database
            displayName: Database governance
          - script: npm run edrp:operate -- --skip-reset
            displayName: EDRP operate
          - script: npm run lint
            displayName: Lint
          - script: npm run test
            displayName: Tests
          - script: npm run build
            displayName: Build
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: src/lib/devops/data
              artifact: edrp-data
            condition: always()

  - stage: Staging
    displayName: Staging Gate
    dependsOn: Validate
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: StagingApprove
        environment: staging
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Promote using EDRP release candidate artifacts"
`;
}

function gitlabCi(): string {
  return `# Generated by EDRP — GitLab CI
stages:
  - validate
  - build
  - release

variables:
  NODE_VERSION: "20"

default:
  image: node:\${NODE_VERSION}
  cache:
    key: \${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

edrp_validate:
  stage: validate
  script:
    - npm ci
    - npm run validate:database
    - npm run edrp:operate -- --skip-reset
    - npm run lint
    - npm run test
  artifacts:
    when: always
    paths:
      - src/lib/devops/data/
    expire_in: 14 days

edrp_build:
  stage: build
  needs: [edrp_validate]
  script:
    - npm ci
    - npm run build

edrp_release_gate:
  stage: release
  needs: [edrp_build]
  script:
    - npm ci
    - npx tsx scripts/validate-devops.mts
  only:
    - main
    - master
`;
}

function selfHostedRunner(): string {
  return `#!/usr/bin/env bash
# Generated by EDRP — Self-hosted runner entrypoint
# Requires: Node 20+, npm. Optional: Docker + Supabase CLI for live reset.
set -euo pipefail

ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

export SKIP_RESET="\${SKIP_RESET:-1}"

echo "[EDRP] Installing dependencies"
npm ci

echo "[EDRP] Database governance"
npm run validate:database

if [[ "$SKIP_RESET" == "1" ]]; then
  echo "[EDRP] Operational release (skip live reset)"
  npm run edrp:operate -- --skip-reset
else
  echo "[EDRP] Operational release (full lifecycle)"
  npm run edrp:operate
fi

echo "[EDRP] Lint / test / build"
npm run lint
npm run test
npm run build

echo "[EDRP] Complete — see src/lib/devops/data/snapshots/latest.json"
`;
}

/**
 * Write production-ready CI/CD blueprints generated from DevOps Engine contracts.
 */
export function generateCiCdBlueprints(cwd = process.cwd()): {
  provider: CiProvider;
  path: string;
  blueprint: ReturnType<typeof buildCiBlueprint>;
}[] {
  const outputs: {
    provider: CiProvider;
    path: string;
    blueprint: ReturnType<typeof buildCiBlueprint>;
  }[] = [];

  const githubPath = join(cwd, ".github", "workflows", "edrp.yml");
  writeFile(githubPath, githubWorkflow());
  outputs.push({
    provider: "github_actions",
    path: githubPath,
    blueprint: buildCiBlueprint("github_actions"),
  });

  const azurePath = join(cwd, "azure-pipelines.yml");
  writeFile(azurePath, azurePipelines());
  outputs.push({
    provider: "azure_devops",
    path: azurePath,
    blueprint: buildCiBlueprint("azure_devops"),
  });

  const gitlabPath = join(cwd, ".gitlab-ci.yml");
  writeFile(gitlabPath, gitlabCi());
  outputs.push({
    provider: "gitlab_ci",
    path: gitlabPath,
    blueprint: buildCiBlueprint("gitlab_ci"),
  });

  const selfHostedPath = join(cwd, "ci", "self-hosted", "edrp.sh");
  writeFile(selfHostedPath, selfHostedRunner());
  outputs.push({
    provider: "self_hosted",
    path: selfHostedPath,
    blueprint: buildCiBlueprint("self_hosted"),
  });

  return outputs;
}

export function ensureCiCdBlueprints(cwd = process.cwd()): string[] {
  return generateCiCdBlueprints(cwd).map((entry) => entry.path);
}

export function ciCdBlueprintStatus(cwd = process.cwd()): {
  provider: CiProvider;
  present: boolean;
  path: string;
}[] {
  const expected: Array<{ provider: CiProvider; path: string }> = [
    { provider: "github_actions", path: join(cwd, ".github", "workflows", "edrp.yml") },
    { provider: "azure_devops", path: join(cwd, "azure-pipelines.yml") },
    { provider: "gitlab_ci", path: join(cwd, ".gitlab-ci.yml") },
    { provider: "self_hosted", path: join(cwd, "ci", "self-hosted", "edrp.sh") },
  ];
  return expected.map((entry) => ({
    ...entry,
    present: existsSync(entry.path),
  }));
}
