import type { AiModuleId } from "@/lib/ai/constants";
import type { AiModuleKnowledge } from "@/lib/ai/types/knowledge";
import { COMPANY_PERMISSIONS } from "@/constants/company";
import { ENGAGEMENT_PERMISSIONS } from "@/constants/engagement";
import { PLANNING_PERMISSIONS } from "@/constants/planning";
import { MATERIALITY_PERMISSIONS } from "@/constants/materiality";
import { RISK_ASSESSMENT_PERMISSIONS } from "@/constants/risk-assessment";
import { FIELDWORK_PERMISSIONS } from "@/constants/fieldwork";
import { REVIEW_PERMISSIONS } from "@/constants/review";
import { COMPLETION_PERMISSIONS } from "@/constants/completion";
import { REPORTING_PERMISSIONS } from "@/constants/reporting";
import { OPINION_PERMISSIONS } from "@/constants/opinion";
import { FINANCIAL_STATEMENTS_PERMISSIONS } from "@/constants/financial-statements";
import { TRIAL_BALANCE_PERMISSIONS } from "@/constants/trial-balance";
import { UAIE_PERMISSIONS } from "@/constants/uaie";

function values(obj: Record<string, string>): string[] {
  return Object.values(obj);
}

export const AI_MODULE_CATALOG: readonly AiModuleKnowledge[] = [
  {
    id: "dashboard",
    name: "Dashboard",
    purpose: "Workspace command center for KPIs, activity, and module entry points.",
    inputs: ["workspace context", "activity feed", "kpi aggregates"],
    outputs: ["executive summary", "navigation shortcuts", "attention items"],
    dependencies: [],
    workflow: ["load workspace", "render KPIs", "surface pending reviews"],
    permissions: [],
    navigation: { basePath: "/app/dashboard", sections: ["overview"] },
    relatedModules: ["companies", "engagements", "import-intelligence"],
  },
  {
    id: "companies",
    name: "Companies",
    purpose: "Manage audited entities, identity, reporting profile, and company workspace.",
    inputs: ["company profile", "settings", "validation state"],
    outputs: ["company workspace", "entity metadata"],
    dependencies: [],
    workflow: ["create company", "configure reporting", "validate", "open workspace"],
    permissions: values(COMPANY_PERMISSIONS),
    navigation: {
      basePath: "/app/companies",
      sections: ["overview", "identity", "reporting", "settings"],
    },
    relatedModules: ["engagements", "uaie", "dashboard"],
  },
  {
    id: "engagements",
    name: "Engagements",
    purpose: "Lifecycle container for audit and assurance engagements.",
    inputs: ["engagement metadata", "members", "lifecycle status"],
    outputs: ["engagement workspace", "phase pipeline"],
    dependencies: ["companies"],
    workflow: ["create", "staff", "advance lifecycle", "close"],
    permissions: values(ENGAGEMENT_PERMISSIONS),
    navigation: {
      basePath: "/app/engagements",
      sections: [
        "overview",
        "members",
        "planning",
        "materiality",
        "risk-assessment",
        "fieldwork",
        "review",
        "completion",
        "reporting",
        "opinion",
        "trial-balance",
        "financial-statements",
        "history",
        "settings",
      ],
    },
    relatedModules: [
      "planning",
      "materiality",
      "risk-assessment",
      "fieldwork",
      "review",
      "completion",
      "reporting",
      "opinion",
      "trial-balance",
      "financial-statements",
    ],
  },
  {
    id: "planning",
    name: "Planning",
    purpose: "Document audit strategy, scope, team readiness, and planning checklist.",
    inputs: ["engagement", "strategy", "scope", "documents"],
    outputs: ["audit plan", "planning status", "checklist progress"],
    dependencies: ["engagements"],
    workflow: ["create plan", "complete checklist", "submit", "approve"],
    permissions: values(PLANNING_PERMISSIONS),
    navigation: {
      basePath: "/app/engagements/[slug]/planning",
      sections: ["overview", "strategy", "objectives", "scope", "documents", "history", "settings"],
    },
    relatedModules: ["materiality", "risk-assessment", "engagements"],
  },
  {
    id: "materiality",
    name: "Materiality",
    purpose: "ISA 320 materiality thresholds, benchmarks, and calculations.",
    inputs: ["benchmarks", "financial inputs", "planning approval"],
    outputs: ["overall/performance/trivial thresholds", "versions"],
    dependencies: ["planning"],
    workflow: ["create package", "set benchmarks", "calculate", "submit", "approve"],
    permissions: values(MATERIALITY_PERMISSIONS),
    navigation: {
      basePath: "/app/engagements/[slug]/materiality",
      sections: ["overview", "benchmarks", "calculations", "comments", "history", "settings"],
    },
    relatedModules: ["planning", "risk-assessment"],
  },
  {
    id: "risk-assessment",
    name: "Risk Assessment",
    purpose: "Identify, score, and respond to audit risks across assertions.",
    inputs: ["risk register", "ratings", "responses", "materiality"],
    outputs: ["risk assessment package", "heatmap", "significant risks"],
    dependencies: ["materiality"],
    workflow: ["create assessment", "register risks", "rate", "respond", "submit", "approve"],
    permissions: values(RISK_ASSESSMENT_PERMISSIONS),
    navigation: {
      basePath: "/app/engagements/[slug]/risk-assessment",
      sections: [
        "overview",
        "inherent-risks",
        "significant-risks",
        "heatmap",
        "matrix",
        "responses",
        "history",
        "settings",
      ],
    },
    relatedModules: ["materiality", "fieldwork"],
  },
  {
    id: "fieldwork",
    name: "Fieldwork",
    purpose: "Execute audit procedures, working papers, evidence, and findings.",
    inputs: ["program", "procedures", "evidence", "risk links"],
    outputs: ["working papers", "findings", "progress"],
    dependencies: ["risk-assessment"],
    workflow: ["initiate", "execute procedures", "attach evidence", "raise findings", "clear"],
    permissions: values(FIELDWORK_PERMISSIONS),
    navigation: {
      basePath: "/app/engagements/[slug]/fieldwork",
      sections: [
        "overview",
        "program",
        "procedures",
        "working-papers",
        "evidence",
        "findings",
        "notes",
        "history",
        "settings",
      ],
    },
    relatedModules: ["risk-assessment", "review", "completion"],
  },
  {
    id: "review",
    name: "Review",
    purpose: "Engagement review queue for pending, returned, and resolved review items.",
    inputs: ["review items", "fieldwork status", "comments"],
    outputs: ["review package", "clearance state"],
    dependencies: ["fieldwork"],
    workflow: ["create package", "queue items", "review", "return", "approve"],
    permissions: values(REVIEW_PERMISSIONS),
    navigation: {
      basePath: "/app/engagements/[slug]/review",
      sections: ["overview", "review-queue", "open-findings", "pending-reviews", "history", "settings"],
    },
    relatedModules: ["fieldwork", "completion"],
  },
  {
    id: "completion",
    name: "Completion",
    purpose: "Completion checklist, outstanding items, and final analytics before reporting.",
    inputs: ["checklist", "outstanding items", "review approval"],
    outputs: ["completion package", "clearance"],
    dependencies: ["review"],
    workflow: ["create package", "resolve outstanding", "submit", "approve"],
    permissions: values(COMPLETION_PERMISSIONS),
    navigation: {
      basePath: "/app/engagements/[slug]/completion",
      sections: ["overview", "checklist", "outstanding-items", "management-letter", "history", "settings"],
    },
    relatedModules: ["review", "reporting"],
  },
  {
    id: "reporting",
    name: "Reporting",
    purpose: "Assemble engagement reporting sections, findings narrative, and management letter.",
    inputs: ["sections", "completion approval", "findings"],
    outputs: ["reporting package", "section drafts"],
    dependencies: ["completion"],
    workflow: ["create package", "draft sections", "submit", "approve"],
    permissions: values(REPORTING_PERMISSIONS),
    navigation: {
      basePath: "/app/engagements/[slug]/reporting",
      sections: [
        "overview",
        "executive-summary",
        "audit-findings",
        "management-letter",
        "history",
        "settings",
      ],
    },
    relatedModules: ["completion", "opinion"],
  },
  {
    id: "opinion",
    name: "Opinion",
    purpose: "Document auditor's opinion type, basis, KAMs, and responsibilities.",
    inputs: ["opinion sections", "reporting approval"],
    outputs: ["opinion package", "opinion draft"],
    dependencies: ["reporting"],
    workflow: ["create package", "select opinion type", "draft sections", "submit", "approve"],
    permissions: values(OPINION_PERMISSIONS),
    navigation: {
      basePath: "/app/engagements/[slug]/opinion",
      sections: [
        "overview",
        "opinion-type",
        "basis-for-opinion",
        "key-audit-matters",
        "history",
        "settings",
      ],
    },
    relatedModules: ["reporting", "financial-statements"],
  },
  {
    id: "financial-statements",
    name: "Financial Statements",
    purpose: "Structured IFRS financial statement packages linked to trial balance.",
    inputs: ["statement sections", "lines", "values", "approved trial balance"],
    outputs: ["FS package", "cross-references", "exports"],
    dependencies: ["trial-balance", "opinion"],
    workflow: ["create package", "load from TB", "edit sections", "submit", "approve", "publish"],
    permissions: values(FINANCIAL_STATEMENTS_PERMISSIONS),
    navigation: {
      basePath: "/app/engagements/[slug]/financial-statements",
      sections: [
        "overview",
        "balance-sheet",
        "income-statement",
        "cash-flow-statement",
        "notes-links",
        "history",
        "settings",
      ],
    },
    relatedModules: ["trial-balance", "opinion"],
  },
  {
    id: "trial-balance",
    name: "Trial Balance",
    purpose: "Enterprise trial balance engine built from UAIE normalized datasets.",
    inputs: ["UAIE staged import", "adjustments", "mappings", "periods"],
    outputs: ["TB package", "hierarchy", "validated balances"],
    dependencies: ["uaie", "engagements"],
    workflow: ["create from import", "classify", "adjust", "validate", "approve"],
    permissions: values(TRIAL_BALANCE_PERMISSIONS),
    navigation: {
      basePath: "/app/engagements/[slug]/trial-balance",
      sections: [
        "overview",
        "accounts",
        "hierarchy",
        "adjustments",
        "mappings",
        "validation",
        "history",
        "settings",
      ],
    },
    relatedModules: ["uaie", "financial-statements"],
  },
  {
    id: "uaie",
    name: "UAIE",
    purpose: "Universal Accounting Import Engine for ERP workbook ingestion and normalization.",
    inputs: ["workbook upload", "column mappings", "validation rules"],
    outputs: ["import sessions", "normalized rows", "mapping profiles"],
    dependencies: ["companies"],
    workflow: ["upload", "detect", "map", "validate", "stage"],
    permissions: values(UAIE_PERMISSIONS),
    navigation: {
      basePath: "/app/companies/[slug]/import",
      sections: ["upload", "session", "mapping", "validation"],
    },
    relatedModules: ["import-intelligence", "trial-balance", "companies"],
  },
  {
    id: "import-intelligence",
    name: "Import Intelligence",
    purpose: "Self-learning import intelligence: dictionaries, fingerprints, and approvals.",
    inputs: ["unknown headers", "dictionary entries", "fingerprints", "sessions"],
    outputs: ["approved dictionary", "learning events", "analytics"],
    dependencies: ["uaie"],
    workflow: ["review unknowns", "approve dictionary", "promote templates", "audit"],
    permissions: [
      UAIE_PERMISSIONS.READ,
      UAIE_PERMISSIONS.REVIEW,
      UAIE_PERMISSIONS.APPROVE,
      UAIE_PERMISSIONS.ADMIN,
      UAIE_PERMISSIONS.LEARN,
    ],
    navigation: {
      basePath: "/app/import-intelligence",
      sections: [
        "overview",
        "sessions",
        "dictionary",
        "unknown-headers",
        "fingerprints",
        "analytics",
        "admin",
      ],
    },
    relatedModules: ["uaie", "dashboard"],
  },
  {
    id: "settings",
    name: "Settings",
    purpose: "Organization, workspace, and user preference configuration surfaces.",
    inputs: ["organization settings", "workspace settings", "user preferences"],
    outputs: ["persisted settings"],
    dependencies: [],
    workflow: ["open settings", "edit", "save"],
    permissions: [],
    navigation: { basePath: "/app/settings", sections: ["general", "security", "locale"] },
    relatedModules: ["users", "permissions"],
  },
  {
    id: "users",
    name: "Users",
    purpose: "User directory and membership administration within the tenant.",
    inputs: ["user profiles", "memberships"],
    outputs: ["user list", "membership assignments"],
    dependencies: ["permissions"],
    workflow: ["invite", "assign roles", "deactivate"],
    permissions: [],
    navigation: { basePath: "/app/users", sections: ["directory", "invites"] },
    relatedModules: ["permissions", "settings"],
  },
  {
    id: "permissions",
    name: "Permissions",
    purpose: "Role and permission governance for workspace authorization.",
    inputs: ["roles", "permission codes", "role assignments"],
    outputs: ["authorization matrix"],
    dependencies: [],
    workflow: ["review roles", "grant permissions", "audit access"],
    permissions: [],
    navigation: { basePath: "/app/permissions", sections: ["roles", "matrix"] },
    relatedModules: ["users", "settings"],
  },
] as const satisfies readonly AiModuleKnowledge[];

export function getAiModuleKnowledge(id: AiModuleId): AiModuleKnowledge | undefined {
  return AI_MODULE_CATALOG.find((module) => module.id === id);
}
