#!/usr/bin/env bash
# Generated by EDRP — Self-hosted runner entrypoint
# Requires: Node 20+, npm. Optional: Docker + Supabase CLI for live reset.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

export SKIP_RESET="${SKIP_RESET:-1}"

echo "[EDRP] Installing dependencies"
npm ci

echo "[EDRP] Database governance"
npm run validate:database

if [[ "$SKIP_RESET" == "1" ]]; then
  echo "[EDRP] Operational release (skip live reset)"
  npm run edrp:operate -- --skip-reset
else
  echo "[EDRP] Operational release (full lifecycle)"
  npm run edrp:operate
fi

echo "[EDRP] Lint / test / build"
npm run lint
npm run test
npm run build

echo "[EDRP] Complete — see src/lib/devops/data/snapshots/latest.json"
