import {
  emptyEvidence,
  type PlatformModuleDefinition,
} from "@/lib/platform-registry/modules";

const STAMP = "2026-07-13T00:00:00.000Z";

/**
 * Platform module catalog.
 * Evidence flags reflect shipped artifacts only — never percentages.
 */
export const PLATFORM_MODULE_CATALOG: PlatformModuleDefinition[] = [
  {
    id: "capability-registry",
    name: "Enterprise Capability Registry",
    domain: "platform",
    dependencies: [],
    children: ["platform-registry"],
    parent: null,
    owner: "platform",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: false,
      enterprise: true,
      localization: false,
      ui: true,
      workflow: false,
      tests: true,
      permissions: false,
      database: false,
      integration: true,
    }),
  },
  {
    id: "platform-registry",
    name: "Enterprise Platform Registry",
    domain: "platform",
    dependencies: ["capability-registry"],
    children: [],
    parent: null,
    owner: "platform",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: true,
      enterprise: true,
      localization: false,
      ui: false,
      workflow: false,
      tests: true,
      permissions: false,
      database: false,
      integration: true,
    }),
  },
  {
    id: "auth",
    name: "Authentication & Authorization",
    domain: "security",
    dependencies: [],
    children: [],
    parent: null,
    owner: "platform",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: true,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "organization",
    name: "Organization Administration",
    domain: "tenant",
    dependencies: ["auth"],
    children: ["workspace"],
    parent: null,
    owner: "platform",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: true,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "workspace",
    name: "Workspace Administration",
    domain: "tenant",
    dependencies: ["organization"],
    children: ["company"],
    parent: "organization",
    owner: "platform",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: true,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "company",
    name: "Company Administration",
    domain: "tenant",
    dependencies: ["workspace"],
    children: ["engagement"],
    parent: "workspace",
    owner: "platform",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: true,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "engagement",
    name: "Engagement Workspace",
    domain: "audit",
    dependencies: ["company"],
    children: [
      "planning",
      "materiality",
      "risk-assessment",
      "fieldwork",
      "review",
      "completion",
      "reporting",
      "opinion",
      "trial-balance",
      "fs-mapping",
      "fs-rendering",
      "ifrs-notes",
      "financial-statements",
    ],
    parent: "company",
    owner: "audit",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: true,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "planning",
    name: "Audit Planning",
    domain: "audit",
    dependencies: ["engagement"],
    children: [],
    parent: "engagement",
    owner: "audit",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: true,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "materiality",
    name: "Materiality Engine",
    domain: "audit",
    dependencies: ["engagement", "planning"],
    children: [],
    parent: "engagement",
    owner: "audit",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: false,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "risk-assessment",
    name: "Risk Assessment",
    domain: "audit",
    dependencies: ["engagement", "planning"],
    children: [],
    parent: "engagement",
    owner: "audit",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: false,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "fieldwork",
    name: "Fieldwork",
    domain: "audit",
    dependencies: ["engagement", "risk-assessment"],
    children: [],
    parent: "engagement",
    owner: "audit",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: true,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "review",
    name: "Review",
    domain: "audit",
    dependencies: ["engagement", "fieldwork"],
    children: [],
    parent: "engagement",
    owner: "audit",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: true,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: false,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "completion",
    name: "Completion",
    domain: "audit",
    dependencies: ["engagement", "review"],
    children: [],
    parent: "engagement",
    owner: "audit",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: false,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: false,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "reporting",
    name: "Reporting",
    domain: "audit",
    dependencies: ["engagement", "completion"],
    children: [],
    parent: "engagement",
    owner: "audit",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: false,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: false,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "opinion",
    name: "Audit Opinion",
    domain: "audit",
    dependencies: ["engagement", "reporting"],
    children: [],
    parent: "engagement",
    owner: "audit",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: false,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: false,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "trial-balance",
    name: "Trial Balance",
    domain: "financial",
    dependencies: ["engagement", "uaie"],
    children: ["fs-mapping"],
    parent: "engagement",
    owner: "financial",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: false,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "fs-mapping",
    name: "Financial Statement Mapping Engine",
    domain: "financial",
    dependencies: ["trial-balance"],
    children: ["fs-rendering", "ifrs-notes"],
    parent: "engagement",
    owner: "financial",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: false,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "fs-rendering",
    name: "Financial Statement Rendering Engine",
    domain: "financial",
    dependencies: ["fs-mapping"],
    children: [],
    parent: "engagement",
    owner: "financial",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: false,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "ifrs-notes",
    name: "Enterprise IFRS Notes Engine",
    domain: "financial",
    dependencies: ["fs-mapping"],
    children: [],
    parent: "engagement",
    owner: "financial",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: false,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "financial-statements",
    name: "Financial Statements Package",
    domain: "financial",
    dependencies: ["engagement"],
    children: [],
    parent: "engagement",
    owner: "financial",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: false,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: false,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "uaie",
    name: "Universal Audit Import Engine",
    domain: "import",
    dependencies: ["engagement"],
    children: [],
    parent: null,
    owner: "platform",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: false,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "ai-platform",
    name: "AI Platform Stack",
    domain: "ai",
    dependencies: ["auth", "workspace"],
    children: [],
    parent: null,
    owner: "ai",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: true,
      enterprise: true,
      localization: true,
      ui: true,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "audit-trail",
    name: "Audit Event Trail",
    domain: "security",
    dependencies: ["auth"],
    children: [],
    parent: null,
    owner: "platform",
    createdAt: STAMP,
    updatedAt: STAMP,
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: true,
      enterprise: true,
      localization: false,
      ui: false,
      workflow: true,
      tests: true,
      permissions: true,
      database: true,
      integration: true,
    }),
  },
  {
    id: "devops",
    name: "Enterprise DevOps & Release Platform",
    domain: "platform",
    dependencies: ["capability-registry", "platform-registry"],
    children: [],
    parent: null,
    owner: "platform",
    createdAt: "2026-07-16T00:00:00.000Z",
    updatedAt: "2026-07-16T00:00:00.000Z",
    evidence: emptyEvidence({
      planning: true,
      foundation: true,
      production: false,
      enterprise: true,
      localization: false,
      ui: false,
      workflow: true,
      tests: true,
      permissions: false,
      database: true,
      integration: true,
    }),
  },
];

export function getCatalogDefinition(id: string): PlatformModuleDefinition | undefined {
  return PLATFORM_MODULE_CATALOG.find((module) => module.id === id);
}
