import type { AiHostActionDefinition } from "@/lib/ai/host/types";

function def(
  partial: AiHostActionDefinition,
): AiHostActionDefinition {
  return partial;
}

/**
 * Host Action Registry catalog — metadata only.
 * Invokers are bound server-side. Never repositories.
 */
export const AI_HOST_ACTION_CATALOG: readonly AiHostActionDefinition[] = [
  def({
    id: "host.company.create",
    title: "Create Company",
    description: "Create a company via registered server action.",
    serverActionId: "company.create",
    moduleId: "companies",
    riskLevel: "medium",
    permission: { anyOf: ["companies.create"], requireWorkspace: true },
    undoAvailable: true,
    compensationStrategy: "compensating_action",
    toolIdHints: ["tool.action.create", "tool.repository.companies"],
    entityTypes: ["company"],
  }),
  def({
    id: "host.company.update",
    title: "Update Company",
    description: "Update a company via registered server action.",
    serverActionId: "company.update",
    moduleId: "companies",
    riskLevel: "medium",
    permission: { anyOf: ["companies.update"], requireWorkspace: true, requireCompany: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.update", "tool.repository.companies"],
    entityTypes: ["company"],
  }),
  def({
    id: "host.company.archive",
    title: "Archive Company",
    description: "Archive a company via registered server action.",
    serverActionId: "company.archive",
    moduleId: "companies",
    riskLevel: "high",
    permission: { anyOf: ["companies.archive"], requireWorkspace: true, requireCompany: true },
    undoAvailable: true,
    compensationStrategy: "restore",
    toolIdHints: ["tool.action.archive", "tool.repository.companies"],
    entityTypes: ["company"],
  }),
  def({
    id: "host.engagement.create",
    title: "Create Engagement",
    description: "Create an engagement via registered server action.",
    serverActionId: "engagement.create",
    moduleId: "engagements",
    riskLevel: "medium",
    permission: { anyOf: ["engagements.create"], requireWorkspace: true },
    undoAvailable: true,
    compensationStrategy: "compensating_action",
    toolIdHints: ["tool.action.create", "tool.repository.engagements"],
    entityTypes: ["engagement"],
  }),
  def({
    id: "host.engagement.update",
    title: "Update Engagement",
    description: "Update an engagement via registered server action.",
    serverActionId: "engagement.update",
    moduleId: "engagements",
    riskLevel: "medium",
    permission: { anyOf: ["engagements.update"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.update", "tool.repository.engagements"],
    entityTypes: ["engagement"],
  }),
  def({
    id: "host.engagement.archive",
    title: "Archive Engagement",
    description: "Archive an engagement via registered server action.",
    serverActionId: "engagement.archive",
    moduleId: "engagements",
    riskLevel: "high",
    permission: { anyOf: ["engagements.archive"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: true,
    compensationStrategy: "restore",
    toolIdHints: ["tool.action.archive", "tool.repository.engagements"],
    entityTypes: ["engagement"],
  }),
  def({
    id: "host.planning.create",
    title: "Create Planning",
    description: "Create planning package via registered server action.",
    serverActionId: "planning.create",
    moduleId: "planning",
    riskLevel: "medium",
    permission: { anyOf: ["planning.create"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.create", "tool.repository.planning"],
    entityTypes: ["planning_package"],
  }),
  def({
    id: "host.planning.update",
    title: "Update Planning",
    description: "Update planning via registered server action.",
    serverActionId: "planning.update",
    moduleId: "planning",
    riskLevel: "medium",
    permission: { anyOf: ["planning.update"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.update", "tool.repository.planning"],
    entityTypes: ["planning_package"],
  }),
  def({
    id: "host.materiality.create",
    title: "Create Materiality",
    description: "Create materiality package via registered server action.",
    serverActionId: "materiality.create",
    moduleId: "materiality",
    riskLevel: "medium",
    permission: { anyOf: ["materiality.create"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.create", "tool.repository.materiality"],
    entityTypes: ["materiality_package"],
  }),
  def({
    id: "host.materiality.update",
    title: "Update Materiality",
    description: "Update materiality via registered server action.",
    serverActionId: "materiality.update",
    moduleId: "materiality",
    riskLevel: "medium",
    permission: { anyOf: ["materiality.update"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.update", "tool.repository.materiality"],
    entityTypes: ["materiality_package"],
  }),
  def({
    id: "host.risk.create",
    title: "Create Risk",
    description: "Create risk assessment item via registered server action.",
    serverActionId: "risk.create",
    moduleId: "risk-assessment",
    riskLevel: "medium",
    permission: { anyOf: ["risk.create", "risk_assessment.create"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.create", "tool.repository.risk"],
    entityTypes: ["risk"],
  }),
  def({
    id: "host.risk.update",
    title: "Update Risk",
    description: "Update risk via registered server action.",
    serverActionId: "risk.update",
    moduleId: "risk-assessment",
    riskLevel: "medium",
    permission: { anyOf: ["risk.update", "risk_assessment.update"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.update", "tool.repository.risk"],
    entityTypes: ["risk"],
  }),
  def({
    id: "host.fieldwork.create",
    title: "Create Fieldwork",
    description: "Create fieldwork package via registered server action.",
    serverActionId: "fieldwork.create",
    moduleId: "fieldwork",
    riskLevel: "medium",
    permission: { anyOf: ["fieldwork.create"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.create", "tool.repository.fieldwork"],
    entityTypes: ["fieldwork_package"],
  }),
  def({
    id: "host.fieldwork.update",
    title: "Update Fieldwork",
    description: "Update fieldwork via registered server action.",
    serverActionId: "fieldwork.update",
    moduleId: "fieldwork",
    riskLevel: "medium",
    permission: { anyOf: ["fieldwork.update"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.update", "tool.repository.fieldwork"],
    entityTypes: ["fieldwork_package"],
  }),
  def({
    id: "host.review.create",
    title: "Create Review",
    description: "Create review package via registered server action.",
    serverActionId: "review.create",
    moduleId: "review",
    riskLevel: "medium",
    permission: { anyOf: ["review.create"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.create", "tool.repository.review"],
    entityTypes: ["review_package"],
  }),
  def({
    id: "host.review.approve",
    title: "Approve Review",
    description: "Approve review item via registered server action.",
    serverActionId: "review.approve",
    moduleId: "review",
    riskLevel: "high",
    permission: { anyOf: ["review.approve"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.approve", "tool.repository.review"],
    entityTypes: ["review_item"],
  }),
  def({
    id: "host.completion.create",
    title: "Create Completion",
    description: "Create completion package via registered server action.",
    serverActionId: "completion.create",
    moduleId: "completion",
    riskLevel: "medium",
    permission: { anyOf: ["completion.create"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.create", "tool.repository.completion"],
    entityTypes: ["completion_package"],
  }),
  def({
    id: "host.completion.approve",
    title: "Approve Completion",
    description: "Approve completion via registered server action.",
    serverActionId: "completion.approve",
    moduleId: "completion",
    riskLevel: "high",
    permission: { anyOf: ["completion.approve"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.approve", "tool.repository.completion"],
    entityTypes: ["completion_item"],
  }),
  def({
    id: "host.reporting.create",
    title: "Create Reporting",
    description: "Create reporting package via registered server action.",
    serverActionId: "reporting.create",
    moduleId: "reporting",
    riskLevel: "medium",
    permission: { anyOf: ["reporting.create"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.create", "tool.repository.reporting"],
    entityTypes: ["reporting_package"],
  }),
  def({
    id: "host.reporting.approve",
    title: "Approve Reporting",
    description: "Approve reporting via registered server action.",
    serverActionId: "reporting.approve",
    moduleId: "reporting",
    riskLevel: "high",
    permission: { anyOf: ["reporting.approve"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.approve", "tool.repository.reporting"],
    entityTypes: ["report_section"],
  }),
  def({
    id: "host.opinion.create",
    title: "Create Opinion",
    description: "Create opinion package via registered server action.",
    serverActionId: "opinion.create",
    moduleId: "opinion",
    riskLevel: "high",
    permission: { anyOf: ["opinion.create"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.create", "tool.repository.opinion"],
    entityTypes: ["opinion_package"],
  }),
  def({
    id: "host.opinion.approve",
    title: "Approve Opinion",
    description: "Approve opinion via registered server action.",
    serverActionId: "opinion.approve",
    moduleId: "opinion",
    riskLevel: "critical",
    permission: { anyOf: ["opinion.approve"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "none",
    toolIdHints: ["tool.action.approve", "tool.repository.opinion"],
    entityTypes: ["opinion_package"],
  }),
  def({
    id: "host.trial_balance.create",
    title: "Create Trial Balance",
    description: "Create trial balance via registered server action.",
    serverActionId: "trial_balance.create",
    moduleId: "trial-balance",
    riskLevel: "medium",
    permission: { anyOf: ["trial_balance.create"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.create", "tool.repository.trial_balance"],
    entityTypes: ["trial_balance"],
  }),
  def({
    id: "host.financial_statements.create",
    title: "Create Financial Statements",
    description: "Create financial statements package via registered server action.",
    serverActionId: "financial_statements.create",
    moduleId: "financial-statements",
    riskLevel: "medium",
    permission: { anyOf: ["financial_statements.create"], requireWorkspace: true, requireEngagement: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.create", "tool.repository.financial_statements"],
    entityTypes: ["financial_statement_package"],
  }),
  def({
    id: "host.uaie.import",
    title: "UAIE Import",
    description: "Run UAIE import via registered server action.",
    serverActionId: "uaie.import",
    moduleId: "uaie",
    riskLevel: "high",
    permission: { anyOf: ["uaie.import", "uaie.create"], requireWorkspace: true },
    undoAvailable: false,
    compensationStrategy: "manual",
    toolIdHints: ["tool.action.create", "tool.repository.uaie"],
    entityTypes: ["uaie_session"],
  }),
];
