import {
  emptyCapabilityEvidence,
  shippedEvidence,
  type CapabilityDefinition,
} from "@/lib/capability-registry/capabilities";
import type { DomainDefinition } from "@/lib/capability-registry/domains";
import type { ModuleDefinition } from "@/lib/capability-registry/modules";
import type { FeatureDefinition } from "@/lib/capability-registry/features";

const STAMP = "2026-07-13T00:00:00.000Z";

function cap(
  partial: Omit<CapabilityDefinition, "createdAt" | "updatedAt" | "children" | "parent"> & {
    parent?: string | null;
    children?: string[];
  },
): CapabilityDefinition {
  return {
    parent: partial.parent ?? null,
    children: partial.children ?? [],
    createdAt: STAMP,
    updatedAt: STAMP,
    ...partial,
  };
}

export const CAPABILITY_DOMAINS: DomainDefinition[] = [
  {
    id: "platform",
    name: "Platform Core",
    description: "Registry, readiness, and cross-cutting platform services.",
    moduleIds: ["capability-registry", "platform-registry", "audit-trail", "devops"],
  },
  {
    id: "security",
    name: "Security",
    description: "Authentication, authorization, and audit integrity.",
    moduleIds: ["auth"],
  },
  {
    id: "tenant",
    name: "Tenant Administration",
    description: "Organization, workspace, and company administration.",
    moduleIds: ["organization", "workspace", "company"],
  },
  {
    id: "audit",
    name: "Audit Engagement",
    description: "Engagement lifecycle and professional audit workflows.",
    moduleIds: [
      "engagement",
      "planning",
      "materiality",
      "risk-assessment",
      "fieldwork",
      "review",
      "completion",
      "reporting",
      "opinion",
    ],
  },
  {
    id: "financial",
    name: "Financial Data",
    description: "Trial balance, mapping, rendering, and statement packages.",
    moduleIds: ["trial-balance", "fs-mapping", "fs-rendering", "financial-statements"],
  },
  {
    id: "import",
    name: "Import Intelligence",
    description: "Universal audit import and staging.",
    moduleIds: ["uaie"],
  },
  {
    id: "ai",
    name: "AI Platform",
    description: "AI runtime, host execution, and enterprise memory.",
    moduleIds: ["ai-platform"],
  },
];

export const CAPABILITY_MODULES: ModuleDefinition[] = [
  {
    id: "capability-registry",
    domainId: "platform",
    name: "Enterprise Capability Registry",
    description: "Capability-based platform completion and readiness.",
    featureIds: ["capreg-model", "capreg-reporting", "capreg-dashboard"],
    dependencies: [],
  },
  {
    id: "platform-registry",
    domainId: "platform",
    name: "Platform Module Registry",
    description: "Legacy module catalog delegated to capability completion.",
    featureIds: ["preg-catalog"],
    dependencies: ["capability-registry"],
  },
  {
    id: "audit-trail",
    domainId: "platform",
    name: "Audit Event Trail",
    description: "Cross-module audit event emission and storage.",
    featureIds: ["audit-emit"],
    dependencies: ["auth"],
  },
  {
    id: "devops",
    domainId: "platform",
    name: "Enterprise DevOps & Release Platform",
    description: "Deterministic validation pipeline, release gating, and CI/CD orchestration.",
    featureIds: ["edrp-pipeline", "edrp-release", "edrp-dashboard"],
    dependencies: ["capability-registry", "platform-registry"],
  },
  {
    id: "auth",
    domainId: "security",
    name: "Authentication & Authorization",
    description: "Identity, sessions, and permission enforcement.",
    featureIds: ["auth-session", "auth-permissions"],
    dependencies: [],
  },
  {
    id: "organization",
    domainId: "tenant",
    name: "Organization Administration",
    description: "Organization lifecycle and entitlements.",
    featureIds: ["org-admin"],
    dependencies: ["auth"],
  },
  {
    id: "workspace",
    domainId: "tenant",
    name: "Workspace Administration",
    description: "Workspace isolation and membership.",
    featureIds: ["ws-admin"],
    dependencies: ["organization"],
  },
  {
    id: "company",
    domainId: "tenant",
    name: "Company Administration",
    description: "Legal entity and company workspace.",
    featureIds: ["co-admin"],
    dependencies: ["workspace"],
  },
  {
    id: "engagement",
    domainId: "audit",
    name: "Engagement Workspace",
    description: "Engagement shell, navigation, and lifecycle.",
    featureIds: ["eng-shell"],
    dependencies: ["company"],
  },
  {
    id: "planning",
    domainId: "audit",
    name: "Audit Planning",
    description: "Planning packages, workflow, and production completion.",
    featureIds: ["plan-core"],
    dependencies: ["engagement"],
  },
  {
    id: "materiality",
    domainId: "audit",
    name: "Materiality Engine",
    description: "Materiality calculation and workspace.",
    featureIds: ["mat-core"],
    dependencies: ["engagement", "planning"],
  },
  {
    id: "risk-assessment",
    domainId: "audit",
    name: "Risk Assessment",
    description: "Risk identification and assessment workspace.",
    featureIds: ["risk-core"],
    dependencies: ["engagement", "planning"],
  },
  {
    id: "fieldwork",
    domainId: "audit",
    name: "Fieldwork",
    description: "Procedures, working papers, and fieldwork production.",
    featureIds: ["fw-core"],
    dependencies: ["engagement", "risk-assessment"],
  },
  {
    id: "review",
    domainId: "audit",
    name: "Review",
    description: "Review notes and sign-off workflow.",
    featureIds: ["rev-core"],
    dependencies: ["engagement", "fieldwork"],
  },
  {
    id: "completion",
    domainId: "audit",
    name: "Completion",
    description: "Engagement completion command center.",
    featureIds: ["comp-core"],
    dependencies: ["engagement", "review"],
  },
  {
    id: "reporting",
    domainId: "audit",
    name: "Reporting",
    description: "Engagement reporting sections and workflow.",
    featureIds: ["rep-core"],
    dependencies: ["engagement", "completion"],
  },
  {
    id: "opinion",
    domainId: "audit",
    name: "Audit Opinion",
    description: "Opinion drafting and sign-off readiness.",
    featureIds: ["op-core"],
    dependencies: ["engagement", "reporting"],
  },
  {
    id: "trial-balance",
    domainId: "financial",
    name: "Trial Balance",
    description: "Trial balance import, classification, and adjustments.",
    featureIds: ["tb-core"],
    dependencies: ["engagement", "uaie"],
  },
  {
    id: "fs-mapping",
    domainId: "financial",
    name: "Financial Statement Mapping Engine",
    description: "TB → normalized financial statement dataset mapping.",
    featureIds: ["fsme-core"],
    dependencies: ["trial-balance"],
  },
  {
    id: "fs-rendering",
    domainId: "financial",
    name: "Financial Statement Rendering Engine",
    description: "UI rendering of normalized financial statement datasets.",
    featureIds: ["fsre-core"],
    dependencies: ["fs-mapping"],
  },
  {
    id: "financial-statements",
    domainId: "financial",
    name: "Financial Statements Package",
    description: "Statement package workflow (distinct from FSRE).",
    featureIds: ["fsp-core"],
    dependencies: ["engagement"],
  },
  {
    id: "uaie",
    domainId: "import",
    name: "Universal Audit Import Engine",
    description: "Import staging, scanning, and intelligence.",
    featureIds: ["uaie-core"],
    dependencies: ["engagement"],
  },
  {
    id: "ai-platform",
    domainId: "ai",
    name: "AI Platform Stack",
    description: "AI runtime, tools, host execution, and memory.",
    featureIds: ["ai-core"],
    dependencies: ["auth", "workspace"],
  },
];

export const CAPABILITY_FEATURES: FeatureDefinition[] = [
  {
    id: "capreg-model",
    moduleId: "capability-registry",
    domainId: "platform",
    name: "Capability Model & Engine",
    description: "Capability definitions, evidence, and roll-up completion engine.",
    capabilityIds: ["capreg-engine", "capreg-validation"],
  },
  {
    id: "capreg-reporting",
    moduleId: "capability-registry",
    domainId: "platform",
    name: "Capability Reporting",
    description: "Platform readiness reports and roadmap generation.",
    capabilityIds: ["capreg-report", "capreg-roadmap"],
  },
  {
    id: "capreg-dashboard",
    moduleId: "capability-registry",
    domainId: "platform",
    name: "Readiness Dashboard",
    description: "Enterprise dashboard for platform/domain/module readiness.",
    capabilityIds: ["capreg-ui"],
  },
  {
    id: "preg-catalog",
    moduleId: "platform-registry",
    domainId: "platform",
    name: "Module Catalog Bridge",
    description: "Module registry that consumes capability-based completion.",
    capabilityIds: ["preg-bridge"],
  },
  {
    id: "audit-emit",
    moduleId: "audit-trail",
    domainId: "platform",
    name: "Audit Emission",
    description: "emitAuditEvent and AUDIT_ACTIONS registry.",
    capabilityIds: ["audit-emit-core"],
  },
  {
    id: "edrp-pipeline",
    moduleId: "devops",
    domainId: "platform",
    name: "EDRP Validation Pipeline",
    description: "Ordered enterprise validation stages from source to release gate.",
    capabilityIds: ["edrp-pipeline-engine"],
  },
  {
    id: "edrp-release",
    moduleId: "devops",
    domainId: "platform",
    name: "EDRP Release Manager",
    description: "Release candidates, checklists, versioning, and promotion gates.",
    capabilityIds: ["edrp-release-manager"],
  },
  {
    id: "edrp-dashboard",
    moduleId: "devops",
    domainId: "platform",
    name: "EDRP Dashboard",
    description: "DevOps health, readiness, and artifact summary surface.",
    capabilityIds: ["edrp-dashboard-model"],
  },
  {
    id: "auth-session",
    moduleId: "auth",
    domainId: "security",
    name: "Session & Identity",
    description: "Authentication and current-user resolution.",
    capabilityIds: ["auth-session-core"],
  },
  {
    id: "auth-permissions",
    moduleId: "auth",
    domainId: "security",
    name: "Permission Enforcement",
    description: "Permission codes and authorization gates.",
    capabilityIds: ["auth-perm-core"],
  },
  {
    id: "org-admin",
    moduleId: "organization",
    domainId: "tenant",
    name: "Organization Admin",
    description: "Organization CRUD and workspace entitlements.",
    capabilityIds: ["org-admin-core"],
  },
  {
    id: "ws-admin",
    moduleId: "workspace",
    domainId: "tenant",
    name: "Workspace Admin",
    description: "Workspace context and membership.",
    capabilityIds: ["ws-admin-core"],
  },
  {
    id: "co-admin",
    moduleId: "company",
    domainId: "tenant",
    name: "Company Admin",
    description: "Company identity and administration workspace.",
    capabilityIds: ["co-admin-core"],
  },
  {
    id: "eng-shell",
    moduleId: "engagement",
    domainId: "audit",
    name: "Engagement Shell",
    description: "Engagement workspace navigation and lifecycle.",
    capabilityIds: ["eng-shell-core"],
  },
  {
    id: "plan-core",
    moduleId: "planning",
    domainId: "audit",
    name: "Planning Core",
    description: "Planning package foundation through production.",
    capabilityIds: ["plan-workspace"],
  },
  {
    id: "mat-core",
    moduleId: "materiality",
    domainId: "audit",
    name: "Materiality Core",
    description: "Materiality engine and workspace.",
    capabilityIds: ["mat-workspace"],
  },
  {
    id: "risk-core",
    moduleId: "risk-assessment",
    domainId: "audit",
    name: "Risk Core",
    description: "Risk assessment workspace and rules.",
    capabilityIds: ["risk-workspace"],
  },
  {
    id: "fw-core",
    moduleId: "fieldwork",
    domainId: "audit",
    name: "Fieldwork Core",
    description: "Fieldwork procedures and production completion.",
    capabilityIds: ["fw-workspace"],
  },
  {
    id: "rev-core",
    moduleId: "review",
    domainId: "audit",
    name: "Review Core",
    description: "Review workflow and production completion.",
    capabilityIds: ["rev-workspace"],
  },
  {
    id: "comp-core",
    moduleId: "completion",
    domainId: "audit",
    name: "Completion Core",
    description: "Completion command center.",
    capabilityIds: ["comp-workspace"],
  },
  {
    id: "rep-core",
    moduleId: "reporting",
    domainId: "audit",
    name: "Reporting Core",
    description: "Reporting sections and workflow.",
    capabilityIds: ["rep-workspace"],
  },
  {
    id: "op-core",
    moduleId: "opinion",
    domainId: "audit",
    name: "Opinion Core",
    description: "Opinion workspace and workflow.",
    capabilityIds: ["op-workspace"],
  },
  {
    id: "tb-core",
    moduleId: "trial-balance",
    domainId: "financial",
    name: "Trial Balance Core",
    description: "TB package, classification, and adjustments.",
    capabilityIds: ["tb-workspace"],
  },
  {
    id: "fsme-core",
    moduleId: "fs-mapping",
    domainId: "financial",
    name: "FSME Core",
    description: "Mapping engine from TB to normalized dataset.",
    capabilityIds: ["fsme-engine", "fsme-workspace"],
  },
  {
    id: "fsre-core",
    moduleId: "fs-rendering",
    domainId: "financial",
    name: "FSRE Core",
    description: "Presentation rendering engine and workspace.",
    capabilityIds: ["fsre-engine", "fsre-workspace"],
  },
  {
    id: "fsp-core",
    moduleId: "financial-statements",
    domainId: "financial",
    name: "FS Package Core",
    description: "Financial statement package workflow.",
    capabilityIds: ["fsp-workspace"],
  },
  {
    id: "uaie-core",
    moduleId: "uaie",
    domainId: "import",
    name: "UAIE Core",
    description: "Import engine and intelligence center.",
    capabilityIds: ["uaie-workspace"],
  },
  {
    id: "ai-core",
    moduleId: "ai-platform",
    domainId: "ai",
    name: "AI Core",
    description: "AI runtime, tools, host execution, memory.",
    capabilityIds: ["ai-runtime"],
  },
];

export const CAPABILITY_CATALOG: CapabilityDefinition[] = [
  cap({
    id: "capreg-engine",
    domain: "platform",
    module: "capability-registry",
    feature: "capreg-model",
    name: "Capability Completion Engine",
    description: "Roll-up completion from evidence through platform.",
    priority: "critical",
    dependencies: [],
    evidence: emptyCapabilityEvidence({
      backend: true,
      validation: true,
      rules: true,
      tests: true,
      documentation: true,
      integration: true,
      security: true,
    }),
  }),
  cap({
    id: "capreg-validation",
    domain: "platform",
    module: "capability-registry",
    feature: "capreg-model",
    name: "Capability Registry Validation",
    description: "Detect orphans, duplicates, missing links, circular deps.",
    priority: "critical",
    dependencies: ["capreg-engine"],
    evidence: emptyCapabilityEvidence({
      backend: true,
      validation: true,
      rules: true,
      tests: true,
      documentation: true,
      integration: true,
      security: true,
    }),
  }),
  cap({
    id: "capreg-report",
    domain: "platform",
    module: "capability-registry",
    feature: "capreg-reporting",
    name: "Platform Capability Report",
    description: "Domains, modules, features, capabilities, evidence, gaps.",
    priority: "high",
    dependencies: ["capreg-engine"],
    evidence: emptyCapabilityEvidence({
      backend: true,
      validation: true,
      tests: true,
      documentation: true,
      integration: true,
      security: true,
    }),
  }),
  cap({
    id: "capreg-roadmap",
    domain: "platform",
    module: "capability-registry",
    feature: "capreg-reporting",
    name: "Capability Roadmap",
    description: "Completed, in progress, blocked, planned, future lanes.",
    priority: "high",
    dependencies: ["capreg-engine"],
    evidence: emptyCapabilityEvidence({
      backend: true,
      rules: true,
      tests: true,
      documentation: true,
      integration: true,
      security: true,
    }),
  }),
  cap({
    id: "capreg-ui",
    domain: "platform",
    module: "capability-registry",
    feature: "capreg-dashboard",
    name: "Platform Readiness Dashboard",
    description: "Enterprise dashboard for readiness hierarchy.",
    priority: "high",
    dependencies: ["capreg-report"],
    evidence: emptyCapabilityEvidence({
      backend: true,
      ui: true,
      workspace: true,
      localization: false,
      tests: true,
      documentation: true,
      integration: true,
      security: true,
    }),
  }),
  cap({
    id: "preg-bridge",
    domain: "platform",
    module: "platform-registry",
    feature: "preg-catalog",
    name: "Platform Registry Capability Bridge",
    description: "Delegates platform completion to capability registry.",
    priority: "high",
    dependencies: ["capreg-engine"],
    evidence: emptyCapabilityEvidence({
      backend: true,
      tests: true,
      documentation: true,
      integration: true,
      security: true,
    }),
  }),
  cap({
    id: "audit-emit-core",
    domain: "platform",
    module: "audit-trail",
    feature: "audit-emit",
    name: "Audit Event Emission",
    description: "Central audit action constants and emitAuditEvent.",
    priority: "critical",
    dependencies: [],
    evidence: shippedEvidence({ performance: true, workspace: false, ui: false }),
  }),
  cap({
    id: "edrp-pipeline-engine",
    domain: "platform",
    module: "devops",
    feature: "edrp-pipeline",
    name: "EDRP Pipeline Engine",
    description: "Orchestrates migration, SQL foundation, schema, sync, build, and release validation.",
    priority: "critical",
    dependencies: [],
    evidence: emptyCapabilityEvidence({
      backend: true,
      validation: true,
      rules: true,
      tests: true,
      documentation: true,
      integration: true,
      security: true,
      database: true,
      repository: true,
      ui: true,
      workspace: true,
      performance: true,
    }),
  }),
  cap({
    id: "edrp-release-manager",
    domain: "platform",
    module: "devops",
    feature: "edrp-release",
    name: "EDRP Release Manager",
    description: "Release candidates, checklists, versioning, CI/CD blueprints, deployment gates.",
    priority: "critical",
    dependencies: ["edrp-pipeline-engine"],
    evidence: emptyCapabilityEvidence({
      backend: true,
      validation: true,
      rules: true,
      tests: true,
      documentation: true,
      integration: true,
      security: true,
      repository: true,
      ui: true,
      performance: true,
    }),
  }),
  cap({
    id: "edrp-dashboard-model",
    domain: "platform",
    module: "devops",
    feature: "edrp-dashboard",
    name: "EDRP Dashboard Model",
    description: "Aggregated DevOps health, readiness, and artifact reporting.",
    priority: "high",
    dependencies: ["edrp-pipeline-engine"],
    evidence: emptyCapabilityEvidence({
      backend: true,
      validation: true,
      tests: true,
      documentation: true,
      integration: true,
      ui: true,
      workspace: true,
      repository: true,
      performance: true,
    }),
  }),
  cap({
    id: "auth-session-core",
    domain: "security",
    module: "auth",
    feature: "auth-session",
    name: "Auth Session Resolution",
    description: "getCurrentUser and session boundaries.",
    priority: "critical",
    dependencies: [],
    evidence: shippedEvidence({ performance: true }),
  }),
  cap({
    id: "auth-perm-core",
    domain: "security",
    module: "auth",
    feature: "auth-permissions",
    name: "Permission Authorization",
    description: "requirePermissionCodes and RBAC grants.",
    priority: "critical",
    dependencies: ["auth-session-core"],
    evidence: shippedEvidence({ performance: true }),
  }),
  cap({
    id: "org-admin-core",
    domain: "tenant",
    module: "organization",
    feature: "org-admin",
    name: "Organization Administration Workspace",
    description: "Organization lifecycle and admin UI.",
    priority: "critical",
    dependencies: ["auth-perm-core"],
    evidence: shippedEvidence({ performance: true }),
  }),
  cap({
    id: "ws-admin-core",
    domain: "tenant",
    module: "workspace",
    feature: "ws-admin",
    name: "Workspace Administration",
    description: "Workspace context and membership.",
    priority: "critical",
    dependencies: ["org-admin-core"],
    evidence: shippedEvidence({ performance: true }),
  }),
  cap({
    id: "co-admin-core",
    domain: "tenant",
    module: "company",
    feature: "co-admin",
    name: "Company Administration",
    description: "Company identity and admin workspace.",
    priority: "critical",
    dependencies: ["ws-admin-core"],
    evidence: shippedEvidence({ performance: true }),
  }),
  cap({
    id: "eng-shell-core",
    domain: "audit",
    module: "engagement",
    feature: "eng-shell",
    name: "Engagement Workspace Shell",
    description: "Engagement nav, lifecycle, and shell.",
    priority: "critical",
    dependencies: ["co-admin-core"],
    evidence: shippedEvidence({ performance: true }),
  }),
  cap({
    id: "plan-workspace",
    domain: "audit",
    module: "planning",
    feature: "plan-core",
    name: "Planning Workspace",
    description: "Planning foundation through production completion.",
    priority: "critical",
    dependencies: ["eng-shell-core"],
    evidence: shippedEvidence({ performance: true }),
  }),
  cap({
    id: "mat-workspace",
    domain: "audit",
    module: "materiality",
    feature: "mat-core",
    name: "Materiality Workspace",
    description: "Materiality engine and engagement workspace.",
    priority: "high",
    dependencies: ["eng-shell-core", "plan-workspace"],
    evidence: shippedEvidence({ performance: false }),
  }),
  cap({
    id: "risk-workspace",
    domain: "audit",
    module: "risk-assessment",
    feature: "risk-core",
    name: "Risk Assessment Workspace",
    description: "Risk assessment rules and UI.",
    priority: "high",
    dependencies: ["eng-shell-core", "plan-workspace"],
    evidence: shippedEvidence({ performance: false }),
  }),
  cap({
    id: "fw-workspace",
    domain: "audit",
    module: "fieldwork",
    feature: "fw-core",
    name: "Fieldwork Workspace",
    description: "Fieldwork procedures and production completion.",
    priority: "critical",
    dependencies: ["eng-shell-core", "risk-workspace"],
    evidence: shippedEvidence({ performance: true }),
  }),
  cap({
    id: "rev-workspace",
    domain: "audit",
    module: "review",
    feature: "rev-core",
    name: "Review Workspace",
    description: "Review workflow; domain unit tests incomplete.",
    priority: "high",
    dependencies: ["eng-shell-core", "fw-workspace"],
    evidence: shippedEvidence({ tests: false, performance: false }),
  }),
  cap({
    id: "comp-workspace",
    domain: "audit",
    module: "completion",
    feature: "comp-core",
    name: "Completion Workspace",
    description: "Completion command center; tests incomplete.",
    priority: "high",
    dependencies: ["eng-shell-core", "rev-workspace"],
    evidence: shippedEvidence({ tests: false, performance: false }),
  }),
  cap({
    id: "rep-workspace",
    domain: "audit",
    module: "reporting",
    feature: "rep-core",
    name: "Reporting Workspace",
    description: "Reporting sections; tests incomplete.",
    priority: "high",
    dependencies: ["eng-shell-core", "comp-workspace"],
    evidence: shippedEvidence({ tests: false, performance: false }),
  }),
  cap({
    id: "op-workspace",
    domain: "audit",
    module: "opinion",
    feature: "op-core",
    name: "Opinion Workspace",
    description: "Opinion workflow; tests incomplete.",
    priority: "high",
    dependencies: ["eng-shell-core", "rep-workspace"],
    evidence: shippedEvidence({ tests: false, performance: false }),
  }),
  cap({
    id: "tb-workspace",
    domain: "financial",
    module: "trial-balance",
    feature: "tb-core",
    name: "Trial Balance Workspace",
    description: "TB package, classification, adjustments.",
    priority: "critical",
    dependencies: ["eng-shell-core", "uaie-workspace"],
    evidence: shippedEvidence({ performance: false }),
  }),
  cap({
    id: "fsme-engine",
    domain: "financial",
    module: "fs-mapping",
    feature: "fsme-core",
    name: "FSME Mapping Engine",
    description: "Classification, mapping, aggregation, validation, dataset.",
    priority: "critical",
    dependencies: ["tb-workspace"],
    evidence: shippedEvidence({ performance: false, documentation: true }),
  }),
  cap({
    id: "fsme-workspace",
    domain: "financial",
    module: "fs-mapping",
    feature: "fsme-core",
    name: "FSME Workspace",
    description: "Mapping explorer, validation, versions, history.",
    priority: "high",
    dependencies: ["fsme-engine"],
    evidence: shippedEvidence({ performance: false }),
  }),
  cap({
    id: "fsre-engine",
    domain: "financial",
    module: "fs-rendering",
    feature: "fsre-core",
    name: "FSRE Rendering Engine",
    description: "Presentation, layout, formatting, validation engines.",
    priority: "critical",
    dependencies: ["fsme-engine"],
    evidence: shippedEvidence({ performance: false }),
  }),
  cap({
    id: "fsre-workspace",
    domain: "financial",
    module: "fs-rendering",
    feature: "fsre-core",
    name: "FSRE Workspace",
    description: "Statement explorer, layout selector, version center.",
    priority: "high",
    dependencies: ["fsre-engine"],
    evidence: shippedEvidence({ performance: false }),
  }),
  cap({
    id: "fsp-workspace",
    domain: "financial",
    module: "financial-statements",
    feature: "fsp-core",
    name: "Financial Statements Package Workspace",
    description: "Package workflow; domain tests incomplete.",
    priority: "high",
    dependencies: ["eng-shell-core"],
    evidence: shippedEvidence({ tests: false, performance: false }),
  }),
  cap({
    id: "uaie-workspace",
    domain: "import",
    module: "uaie",
    feature: "uaie-core",
    name: "UAIE Workspace",
    description: "Import staging and intelligence center.",
    priority: "critical",
    dependencies: ["eng-shell-core"],
    evidence: shippedEvidence({ performance: false }),
  }),
  cap({
    id: "ai-runtime",
    domain: "ai",
    module: "ai-platform",
    feature: "ai-core",
    name: "AI Platform Runtime",
    description: "Tools, orchestrator, host execution, memory.",
    priority: "critical",
    dependencies: ["auth-session-core", "ws-admin-core"],
    evidence: shippedEvidence({ performance: true }),
  }),
];

export function getCapabilityDefinition(id: string): CapabilityDefinition | undefined {
  return CAPABILITY_CATALOG.find((entry) => entry.id === id);
}
