/** Canonical shared helpers that belong in the Enterprise SQL Foundation. */
export const SQL_FOUNDATION_REQUIRED_HELPERS = [
  "utc_now",
  "auth_user_id",
  "current_user_id",
  "current_workspace_id",
  "current_organization_id",
  "set_updated_at",
  "set_row_version",
  "set_created_by",
  "set_updated_by",
  "is_not_deleted",
  "is_service_role",
  "user_belongs_to_organization",
  "user_belongs_to_workspace",
  "user_organization_ids",
  "user_workspace_ids",
  "is_workspace_member",
  "is_organization_member",
  "user_can_access_workspace",
  "user_can_access_organization",
  "has_permission",
  "has_workspace_permission",
  "soft_delete",
  "restore_deleted",
  "is_active_record",
  "jsonb_merge",
  "jsonb_is_object",
  "is_nonempty_text",
  "is_valid_uuid",
  "simple_search_vector",
  "storage_object_belongs_to_workspace",
  "policy_workspace_read",
  "policy_workspace_write",
  "default_organization_settings",
  "default_workspace_settings",
  "default_company_settings",
] as const;

export const SQL_FOUNDATION_EXTENSIONS = ["pgcrypto", "citext"] as const;

export const SQL_FOUNDATION_ENUMS = [
  "record_status",
  "role_scope",
  "permission_scope",
  "membership_scope",
] as const;

/** Built-in / platform functions that migrations may call without creating. */
export const PLATFORM_SQL_FUNCTIONS = new Set([
  "now",
  "timezone",
  "coalesce",
  "nullif",
  "exists",
  "count",
  "sum",
  "avg",
  "min",
  "max",
  "lower",
  "upper",
  "trim",
  "btrim",
  "char_length",
  "length",
  "substring",
  "replace",
  "split_part",
  "to_jsonb",
  "jsonb_build_object",
  "jsonb_typeof",
  "to_tsvector",
  "gen_random_uuid",
  "current_setting",
  "auth.uid",
  "uid",
  "greatest",
  "least",
  "array_agg",
  "string_agg",
  "bool_or",
  "bool_and",
  "row_to_json",
]);
